# permissions for end users to view alluxioclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alluxiocluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: alluxio-operator
    app.kubernetes.io/part-of: alluxio-operator
    app.kubernetes.io/managed-by: kustomize
  name: alluxiocluster-viewer-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - alluxioclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - alluxioclusters/status
  verbs:
  - get
